# Generated by Django 4.2.13 on 2024-06-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productchildish_color_and_more'),
        ('orders', '0005_alter_orderitem_productmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='productchildish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productchildish'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productcooking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productcooking'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productfeminine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productfeminine'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productheadphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productheadphone'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productlaptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productlaptop'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productoffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productoffice'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productrefriGerator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productrefrigerator'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productwashing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productwashing'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='productmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productmen'),
        ),
    ]
