# Generated by Django 4.2.13 on 2024-08-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0006_orderitem_productchildish_orderitem_productcooking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productchildish',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productcooking',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productfeminine',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productheadphone',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productlaptop',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productmen',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productoffice',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productrefriGerator',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productwashing',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
    ]
