# Generated by Django 4.2.13 on 2024-06-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_comment_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductList',
            new_name='ProductListblog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='productlist',
            new_name='productlistblog',
        ),
    ]
