# Generated by Django 4.2.13 on 2024-06-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_productlist_productlistblog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchildish',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='productfeminine',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='productmen',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
