# Generated by Django 4.2.13 on 2024-06-06 10:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productchildish_color_productfeminine_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchildish',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#8b0000', 'red'), ('#ffff00', 'yellow'), ('#006400', 'green')], default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='productfeminine',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#8b0000', 'red'), ('#ffff00', 'yellow'), ('#006400', 'green')], default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='productmen',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#8b0000', 'red'), ('#ffff00', 'yellow'), ('#006400', 'green')], default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
