# Generated by Django 4.2.13 on 2024-06-06 10:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productchildish_color_productfeminine_color_and_more'),
    ]

   