# Generated by Django 4.2.13 on 2024-06-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productchildish_color_and_more'),
    ]

    
