# Generated by Django 4.2.13 on 2024-06-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productchildish_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productchildish',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productfeminine',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='color',
        ),
    ]
