# Generated by Django 4.2.13 on 2024-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productchildish_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productchildish',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcooking',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeminine',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productheadphone',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productlaptop',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmen',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoffice',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productrefrigerator',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productwashing',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productchildish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productfeminine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productheadphone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productlaptop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoffice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productrefrigerator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productwashing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
