# Generated by Django 4.2.13 on 2024-07-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_page_id_productchildish_page_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeminine',
            name='page_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
