# Generated by Django 4.2.13 on 2024-07-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cartitemfeminine_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='productfeminine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productfeminine'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.DeleteModel(
            name='CartItemfeminine',
        ),
    ]
