# Generated by Django 4.2.13 on 2024-08-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cartitem_productfeminine_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='productfeminine',
        ),
        migrations.AddField(
            model_name='product',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productchildish',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcooking',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeminine',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productheadphone',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productlaptop',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmen',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoffice',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productrefrigerator',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productwashing',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productchildish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productfeminine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productheadphone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productlaptop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoffice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productrefrigerator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productwashing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productmen',
            name='colors',
            field=models.ManyToManyField(blank=True, to='products.color'),
        ),
    ]
