# Generated by Django 4.2.13 on 2024-07-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productfeminine_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='page_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='productfeminine',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
