# Generated by Django 4.2.13 on 2024-08-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_color_remove_cartitem_productfeminine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmen',
            name='colors',
        ),
        migrations.AddField(
            model_name='productmen',
            name='siza',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
