# Generated by Django 4.2.13 on 2024-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productmen_colors_productmen_siza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmen',
            name='siza',
            field=models.IntegerField(),
        ),
    ]
